name: Deploy

on:
  push
runs-on: ubuntu-latest

jobs:
  tag_release:
    if: github.event_name == 'push' && !contains(github.event.commits.*.message[0], '#skip')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
