name: Deploy

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  pre_deployment_test:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: start backend
        working-directory: ./wish-list-backend
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          DbPassword: ${{ secrets.DBPASSWORD }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          npm install
          npm run prod &
      - name: e2e test
        uses: cypress-io/github-action@v2
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          DbPassword: ${{ secrets.DBPASSWORD }}
          SECRET: ${{ secrets.SECRET }}
        with:
          command: npm run cypress:run
          start: npm start
          wait-on: http://localhost:3003
          working-directory: wish-list-frontend

  tag_release:
    if: github.event_name == 'push' && !contains(github.event.commits.*.message[0], '#skip')
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
