name: Tester

on:
  push

jobs:
  testing_pre_deployment_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: start backend
        run: npm run prod
        working-directory: ./wish-list-backend