name: Tester

on:
  push

jobs:
  testing_pre_deployment_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: start backend
        working-directory: ./wish-list-backend
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          DbPassword: ${{ secrets.DBPASSWORD }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          npm install
          npm run prod