name: Tester

on:
  push

jobs:
  testing_pre_deployment_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: start backend
        uses: actions/setup-node@v2
        with:
          node-version: '17'
        run: npm install, npm start
      - name: e2e test
        uses: cypress-io/github-action@v2
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          DbPassword: ${{ secrets.DBPASSWORD }}
          SECRET: ${{ secrets.SECRET }}
        with:
          command: npm run cypress:run
          start: npm run prod, npm run start:front
          wait-on: http://localhost:3003, http://localhost:3000
          working-directory: wish-list-backend